name: noonpool
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  async: ^2.11.0
  base32: ^2.1.3
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  fl_chart: ^0.63.0
  flutter_bloc: ^8.1.3
  flutter_inappwebview: ^5.7.2+3
  flutter_svg: ^2.0.7
  focus_detector: ^2.0.1
  http: ^1.1.0
  intl: ^0.18.1
  localization: ^2.1.0
  lottie: ^2.6.0
  otp: ^3.1.4
  pinput: ^3.0.0
  pull_to_refresh: ^2.0.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  share_plus: ^6.3.4
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_launcher_icons: "0.9.2"
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/mini_logo.png"


flutter:

  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/onboarding/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
