// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4EIR3dHsCKEmjBJi7nPyxg9A4QHwCrBQ',
    appId: '1:928082185030:android:5e5038e7a2b795a223f347',
    messagingSenderId: '928082185030',
    projectId: 'noonpool-001',
    storageBucket: 'noonpool-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABoYrGh0E5sNhhkPUpUpc-84TjOf2WhB8',
    appId: '1:928082185030:ios:071a31cfeaa0d7a523f347',
    messagingSenderId: '928082185030',
    projectId: 'noonpool-001',
    storageBucket: 'noonpool-001.appspot.com',
    iosClientId: '928082185030-hmobsdfndn8imedrnollf2fuat9ddoof.apps.googleusercontent.com',
    iosBundleId: 'com.noonpool.app',
  );
}
